[certstream]
url = "wss://certstream.calidog.io/"

[clickhouse]
host = "localhost"
port = 9000
user = "default"
password = ""
database = "default"

[service]
# Enable systemd watchdog notifications (requires libsystemd-dev and WatchdogSec in service file)
enable_systemd_notify = true
batch_size = 1000
max_batch_age_secs = 5
logging_level = "info"
