[advisories]
unmaintained = "all"
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "0BSD",
    "Unlicense",
    "Unicode-3.0",
    "LGPL-2.1 WITH GCC-exception-2.0"
]