[advisories]
unmaintained = "all"
yanked = "deny"

[bans]
deny = ["openssl-sys"] # Example: ban specific crates if needed

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "0BSD",
    "Unlicense",
    "Unicode-3.0"
]