name: Release binaries

on:
  push:
    tags:
      - 'v*.*.*' # Only run for version tags like v1.2.3
  workflow_dispatch:

jobs:
  build-binaries:
    name: Build binaries for release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Install aarch64 cross-compiler
        run: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: ${{ matrix.target == 'aarch64-unknown-linux-gnu' && 'aarch64-linux-gnu-gcc' || '' }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/certhoover
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
